### ISSUE TITLE
params array

### ISSUE THREAD

**Issue by osben** [ngneat/cashew#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

const params = {brands: [1,2]};
this.http.get (url, {... {params: {... params}}});
URL?brands=1&brands = 2
## Expected behavior
const params = {brands: [1,2]};
this.http.get (url, {... {params: {... params}}});
URL?brands=1

## Minimal reproduction of the problem with instructions
const params = {brands: [1,2]};
this.http.get (url, {... {params: {... params}}});
URL?brands=1

## Environment

<pre><code>
Angular version: 8.2.14

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  10.21
- Platform:  Windows 

Others:
When I add an HttpCacheInterceptorModule to app.module.ts some of my requests stop working correctly,
namely params array cease to work correctly

"@angular/common": "~ 8.2.14",
example:

const params = {brands: [1,2]};
this.http.get (url, {... {params: {... params}}});
url?brands=1&brands=2

with HttpCacheInterceptorModule
url?brands=1
</code></pre>

**Comment by osben** [comment]
this bug occurs when HttpParams is used.

**Comment by itayod** [comment]
Hi @osben I have fixed the bug and released a new version (`1.1.5`) could you please update the and validate it works?

**Comment by osben** [comment]
i am happy. its work. great work
