### ISSUE TITLE
Option to set HttpParams Encoder

### ISSUE THREAD

**Issue by mokipedia** [ngneat/cashew#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently, new HttpParams is called hidden away inside the lib without the possibility to set the encoder

## Expected behavior

being able to set an encoder (at least globally) as HttpParams default encoder does not encode/decode params as expected:
https://github.com/angular/angular/issues/18261

## Minimal reproduction of the problem with instructions

have symbols such as + in the param value

## What is the motivation / use case for changing the behavior?

As the lib abstracts away the creation of http params, a way to correct the encoding is needed.

## Environment

<pre><code>
Angular version: 4+ (tested on 5,6,7,8,9)

Browser:
all browsers
 
For Tooling issues:
- Node version: all versions
- Platform:  tested on mac, linux, windows
</code></pre>

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by mokipedia** [comment]
Yes i will try :)
