### ISSUE TITLE
Add reload$ property to the withCache params interface

### ISSUE THREAD

**Issue by Stefaneek** [ngneat/cashew#18]
Would it make sense to add **reload$** property to the withCache params interface? When it will be set to true, stored data for the specific keys will be replaced with the newest. Now probably the one way to achieve that is manually removing a specific key with CacheManager before making a request.

**Comment by NetanelBasal** [comment]
Can you explain the use case, please?

**Comment by Stefaneek** [comment]
I hold in the cache the data, which changes very rarely. First I set data on the GET request but then on every a PUT request I get changed data back and I would like it to replace the existing one in the cache.

e.g

GET request
`.get<any>(
        exampleUrl,
        withCache({
          key$: 'viewSets',
        })`

PUT request
`.put<any>(
        exampleUrl,
        withCache({
          reload$: true
          key$: 'viewSets',
        })`

**Comment by NetanelBasal** [comment]
So you want to reload if the key is different?

**Comment by Stefaneek** [comment]
I want to reload for the same key. It's made for me sens because I hold data in local storage and I get the same collection for various requests GET and PUT in this case. It will keep my local storage always updated.

**Comment by NetanelBasal** [comment]
> I want to reload for the same key

So what's the point of the cache? I'm not sure I follow.

**Comment by Stefaneek** [comment]
Hmmm maybe my explanation is wrong :D 

90% of request to such data is GET which I want to get from the cache. But sometimes someone can make an update (PUT) and I would like in this case replace the cached data with the newest that the during another GET it will return proper data from local storage.

**Comment by NetanelBasal** [comment]
So call clear cache

**Comment by Stefaneek** [comment]
Ok, it's the option which I have mentioned in the first comment. So you propose to do it like that:

`
    this.cacheManager.delete('viewSets');
   .put<any>( exampleUrl, withCache({key$: 'viewSets' })
`

**Comment by NetanelBasal** [comment]
No, you should put the `exampleUrl`

**Comment by Stefaneek** [comment]
Right now probably I do not follow :).

Url could be whatever you want. For me, the point is that on the GET and PUT I get the same data that I want to hold under one key. But on PUT data change and I want to replace it and sync my local storage. I had the idea that your lib could have such an option build in. I will replace it manually clearing the cache before every PUT and setting it from scratch. Thanks for the discussion.

**Comment by NetanelBasal** [comment]
No problem.

**Comment by shaifulborhan** [comment]
Hi there,

Actually I was looking for this capability as well to force reload the cache from the withCache() method.

In my use case, the GET request results are cached with a TTL of 30 min but there are some scenarios in my app where I would like to force reload the cache before the TTL expires. So I imagine if there's a simple boolean option in the withCache() method that can do this it would be very helpful.

If I understand correctly, the only way to accomplish this right now is to manually calling `this.manager.delete('myGetUrlKey')` method in my service before I made a new GET call to the API.

**Comment by NetanelBasal** [comment]
You are welcome to create a PR
