### ISSUE TITLE
Use withCache() in HttpClient.request()

### ISSUE THREAD

**Issue by alfredo-dotcms** [ngneat/cashew#26]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I've seen in the doc that you can use `withCache()` in HttpClient methods like `.get()`, `.post()`, etc. But when trying to be used on `.request()` https://angular.io/api/common/http/HttpClient#request, is not supported (or maybe I have not found the way)

## Expected behavior

Support to use `withCache()` on `.request()` method

## What is the motivation / use case for changing the behavior?

Being able to use `cashew` with an abstraction method to do http requests

**Comment by NetanelBasal** [comment]
It should work the same - `request({...withCache()})`

**Comment by alfredo-dotcms** [comment]
thank you @NetanelBasal it worked!
