### ISSUE TITLE
Skip auto refresh cache after invalidate

### ISSUE THREAD

**Issue by Adrug** [ngneat/cashew#30]
I suggest skip auto repeat request after invalidate the cache until first call by user the call.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We got a repeat all requests after delete some key/bucker from the cache manager.

## Expected behavior

Add config for prevent auto repeat cached requests

## Enviroment

Angular version: 9.1.2
Cashew version: 1.3.2

**Comment by NetanelBasal** [comment]
What do you mean auto-repeat? Can you elaborate, please?

**Comment by Adrug** [comment]
Sorry, it looks like this was bug in my code^)
