### ISSUE TITLE
Lib dont work in prod mod

### ISSUE THREAD

**Issue by BanannaLopal** [ngneat/cashew#31]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you build a project with the ng build --prod command, the library stops working.

## Expected behavior

Library caches queries in prod mode

## Minimal reproduction of the problem with instructions
AOT:true
ivy:false
<pre>
<code>
    HttpCacheInterceptorModule.forRoot({
      strategy: 'explicit',
      ttl: 10 * 10000,
      responseSerializer(body) {
        return cloneDeep(body);
      }
    })
</code>
</pre>

<pre>
<code>
    return this.http.get<User>(this.API + '/auth/user/', withCache({
      cache$: true,
      key$: USER_CACHE_KEY
    }))
</code>
</pre>

## Environment

<pre><code>
Angular version: 8.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:
</code></pre>

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/cashew#config-options

**Comment by BanannaLopal** [comment]
Uh, I did not use the cashewConfig method
