### ISSUE TITLE
withCache can not add Authorization header

### ISSUE THREAD

**Issue by sysmat** [ngneat/cashew#33]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Can not add HTTP header with  withCache

## What is the motivation / use case for changing the behavior?

```
export interface HttpOptions {
    headers: HttpHeaders;
    params?: HttpParams;
}
```
 I think this kind of interface would be better to easy adding headers or parms with withCache function

## Environment
Angular version: 11.2.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14 
- Platform:  Windows 10

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/cashew/issues/11
