### ISSUE TITLE
Regression: Implicit strategy broken in v2?

### ISSUE THREAD

**Issue by enekonieto** [ngneat/cashew#40]
Implicit strategy seems to require using `withCache()`

In 2.0.1 [cache-interceptor.ts](https://github.com/ngneat/cashew/blob/v2.0.1/projects/ngneat/cashew/src/lib/cache-interceptor.ts) has this:

```
intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const context = request.context.get(CACHE_CONTEXT);

    if (context === undefined) {
      return next.handle(request);
    }
...
```

If I have not misunderstood the logic of the code, this will always return the request unchanged unless you use `withCache()`.

In 1.3.2 [httpCacheInterceptor.ts](https://github.com/ngneat/cashew/blob/v1.3.2/projects/ngneat/cashew/src/lib/httpCacheInterceptor.ts) had a different logic and starts asking `CacheGuard`.

**Comment by NetanelBasal** [comment]
Correct, I will fix it.
