### ISSUE TITLE
How to chain multiple HttpContext

### ISSUE THREAD

**Issue by FabienDehopre** [ngneat/cashew#42]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you use the `withCache()` function in a `HttpClient` method, it needs to be assigned to the `context` option. How do you add something else to the `HttpRequest` context ?

**Comment by NetanelBasal** [comment]
withCache() returns the context - use it.

**Comment by NetanelBasal** [comment]
You're welcome to create a PR
