### ISSUE TITLE
Bug: When using LocalStorage for cache, clear() does not work

### ISSUE THREAD

**Issue by omgitsnes** [ngneat/cashew#76]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using `useHttpCacheLocalStorage` to cache with `LocalStorage` and the request results are being cached with key '@cache-example'.
The culprit seems to theese 2 lines, where i think `createKey()` there shoud not be there:
![image](https://user-images.githubusercontent.com/12531526/187751509-dc22013b-811d-4a86-af5a-3718e09978af.png)

When I try to clear all cached entries with `HttpCacheManager` clear(), it iterates all the keys and ads a new '@cache' prefix making the previous key  `@cahe-@cache-example`: 

![image](https://user-images.githubusercontent.com/12531526/187752136-c005e192-c90d-4eaf-b45c-f50d129399aa.png)

## Expected behavior

Localstorage entries related to cached data should have been deleted.

## Minimal reproduction of the problem with instructions

It is possible to reproduce using the playground app with `useHttpCacheLocalStorage`.

## Environment

<pre><code>
Angular version: 14.0.1
Cashew version: 3.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR with the fix :)
