### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by sambernet** [ngneat/cashew#79]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular 13 is used for the project currently.
The `README.md` doesn't give any information about supported angular versions

## Expected behavior

I am aware that the library `package.json` has a peer dependency towards angular 13+ - so it's possible the library works just fine with angular 14 (which is really cool and should be adopted by more angular 3rd party libs 👍 )

But I'm currently mapping out the migration path for a large project with a lot of dependencies, and I was wondering if `cashew` has already been tested with angular 14? Maybe somebody has experience migrating this already?

Then I thought it would be nice to actually provide angular _compatiblity information_ in the main readme of the repository.

Alternatively upgrading the whole library to angular 14 would also resolve my question, of course 😁 

## Minimal reproduction of the problem with instructions

n/a

## What is the motivation / use case for changing the behavior?

Angular 14 was released on June 02, 2022 and is becoming adopted more and more widely. In November we already expect ng15 to hit the road.
Cashew is one of the last libraries for my specific ng 14 upgrade that is not confirmed yet to be ng 14 compatible.

## Environment

Angular 14

**Comment by NetanelBasal** [comment]
Sounds good :) You're welcome to create a PR.

**Comment by sambernet** [comment]
Dammit, you beat me to it 😂 
Thanks 🚀
