### ISSUE TITLE
Requests that error remain in cache and cannot be cleared

### ISSUE THREAD

**Issue by jmannau** [ngneat/cashew#9]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
If an http request errors (any 400/500 response), the request remains in the queue and cannot be cleared but emptying the cache.

## Expected behavior
And non successful response should not be cached and should be cleared from the queue.

## Minimal reproduction of the problem with instructions
1. Issue a http request that will error. ie: 
```
this.http.get('http://notarealurl.test', withCache())
```
2. Check the httpCacheManage queue. The request remains in the queue. This means if the request is retried the original request is replayed.

## What is the motivation / use case for changing the behavior?

For instance, when requesting an endpoint that is protected by authorisation, the first user may not be able to access the resource (returning 403).  This user logs out and another user logs in. The request is retried, but the original request is issued including the Authorization header from user 1, not the new request with the new Authorization header.

## Suggested Fix

I suggest changing the interceptor like this (https://github.com/ngneat/cashew/blob/master/projects/ngneat/cashew/src/lib/httpCacheInterceptor.ts#L37):
```
tap({
    next: event => {
          if (event instanceof HttpResponse) {
            const cache = this.httpCacheManager._resolveResponse(event);
            this.httpCacheManager._set(key, cache, +ttl);
           }
    },
    // Delete the item from the queue when the request completes
    // This will ensure it is not replayed if the request is cancelled or it errors
    complete: () => {
        queue.delete(key);
    }
}),
```

## Environment

<pre><code>
Angular version: 9.1.3
@ngneat/cashew 1.1.3 

Browser:
- [x] Chrome (desktop) version 81
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12 
- Platform:  Mac

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Sure, do you want to create a PR?

**Comment by jmannau** [comment]
Yeah I’m working on on one at the moment. I will submit shortly.

**Comment by jmannau** [comment]
I have opened a PR https://github.com/ngneat/cashew/pull/10 to fix this. I hope it is acceptable. Thanks for your work.
