### ISSUE TITLE
feat: add modern provide* api-s

### ISSUE THREAD

**Issue by eneajaho** [ngneat/cashew#93]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

Currently we have to use `importProvidersFrom(HttpCacheInterceptorModule.forRoot())` in order to use the lib on apps that are built with standalone bootstrap api-s. 

Also, we need to use `withInterceptorsFromDi()` in the `provideHttpClient()` in order for the cache interceptor to be registered as it's a class based interceptor.

## Expected behavior

Add some new api-s that export the providers using sth like:

`provideHttpCache()`

And inside it we can add all the providers needed for the lib to work, 
So basically we can just add sth like this (that we also can reuse in the module that the lib already uses, so no duplicated code): 

```ts
export const provideHttpCache = (config: Partial<HttpCacheConfig> = {}) => {
  const providers: (Provider | EnvironmentProviders)[] = [
    { provide: HTTP_CACHE_CONFIG, useValue: { ...defaultConfig, ...config } },
    { provide: KeySerializer, useClass: DefaultKeySerializer },
    { provide: HttpCacheStorage, useClass: DefaultHttpCacheStorage },
    { provide: TTLManager, useClass: DefaultTTLManager },
    { provide: HttpCacheGuard, useClass: DefaultHttpCacheGuard },
    { provide: HttpCacheVersions, useClass: DefaultHttpVersions },
    HttpCacheManager,
    RequestsQueue,
    RequestsCache,

    config.skipInterceptorDeclaration 
      ? [] 
      : provideHttpClient(withInterceptors([httpCacheInterceptor])) // --> This is not recommended. 
      
     config.skipInterceptorDeclaration 
      ? [] 
      : { provide: HTTP_INTERCEPTOR_FNS, useValue: httpCacheInterceptor, multi: true } // --> Maybe we can do this in the future
  ];

  return makeEnvironmentProviders(providers);
};
```

## What is the motivation / use case for changing the behavior?
Better align with the direction of Angular libs.

**Comment by eneajaho** [comment]
Regarding registering the interceptor, I opened an issue in the Angular repo as currently there's no way to register an interceptor directly from the library if we use functional interceptors. 

https://github.com/angular/angular/issues/51303

**Comment by shaharkazaz** [comment]
@eneajaho You are welcome to open a PR 🙂

**Comment by eneajaho** [comment]
@shaharkazaz 
Will do, but after I get some more information about the interceptor registering part. 

Maybe we can just fallback to tell the developer to register the interceptor themselves. 

So, it would be sth like: 

`app.config.ts`
```ts 
providers: [
  provideHttpClient(withInterceptors([
    httpCacheInterceptor // --> This will be imported from cashew
  ])),
  provideHttpCache() // --> Register other providers. 
]

```

**Comment by muuvmuuv** [comment]
I think you can already use it like this:

```ts
export function provideHttp(): EnvironmentProviders[] {
  return [
    provideHttpClient(
      withInterceptors([
        logInterceptor,
        tokenInterceptor,
        metaInterceptor,
        errorInterceptor,
      ]),
      withXsrfConfiguration({
        cookieName: 'x-csrf-token',
        headerName: 'X-CSRF-Token',
      }),
      withFetch(),
    ),
    importProvidersFrom(
      HttpCacheInterceptorModule.forRoot({
        ttl: 1000 * 60 * 10,
        strategy: 'explicit',
      }),
    ),
    makeEnvironmentProviders(useHttpCacheLocalStorage),
  ]
}
```

**Comment by JonasDev17** [comment]
I am a bit confused, I configured mine like this:

![image](https://github.com/ngneat/cashew/assets/140613210/42e10624-c117-496e-9d1e-982650075031)

but looking at my localstorage I can only see a few files from assets and two requests being cached. All the other requests are just not being cached.

Am I doing something wrong?

**Comment by JonasDev17** [comment]
I also tried explicit and withCache() and nothing is being cached. Am I missing a header or something?
My backend is dotnet 7.

**Comment by JonasDev17** [comment]
I don't know what changed but its working now....

**Comment by waltercruz** [comment]
could someone provide a clear example on how to configure cashew when using standalone bootstrap? Thanks on advance!

**Comment by muuvmuuv** [comment]
Seems to work with `withInterceptorsFromDi` but my response headers are not existing and no longer HttpHeaders and therefore `.get()` does not work.
