### ISSUE TITLE
docs: compatability matrix?

### ISSUE THREAD

**Issue by Laurens-makel** [ngneat/cashew#98]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I've been looking for a compatability matrix which would map the library's version against the supported Angular versions.

## Expected behavior

Something like the following, this example is taken from RxAngular library. 

![image](https://github.com/ngneat/cashew/assets/37303445/f92c283b-6be0-4780-98a7-1b56856e7115)

## Minimal reproduction of the problem with instructions
None

## What is the motivation / use case for changing the behavior?
Help new users of the library to pick the correct version for their application.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shaharkazaz** [comment]
@Laurens-makel You are welcome to open a PR and add it to the README.
You can find the support in the changelog

**Comment by Laurens-makel** [comment]
> @Laurens-makel You are welcome to open a PR and add it to the README. You can find the support in the changelog

Allright, there you go.

Why are the releases for Angular v15 & v16 skipped....?

**Comment by shaharkazaz** [comment]
@Laurens-makel it wasn't, v3.1.0 requires Angular >13
